import { dirname, resolve } from 'node:path';
import type { LibraryOptions, Plugin, UserConfig } from 'vite';
import { loadConfig, resolveConfig, type ViteMagicConfig } from './config.js';
import { generateEntries } from './generateEntries.js';

export interface ViteMagicPluginOptions extends ViteMagicConfig {
  /** Custom config path, relative to the Vite root. Set to `false` to disable discovery. */
  configFile?: string | false;

  /** Additional Vite library options. `entry` is generated by this plugin. */
  library?: Omit<LibraryOptions, 'entry'>;
}

async function pluginConfig(
  viteRoot: string,
  inlineConfig: ViteMagicConfig,
  configFile: string | false | undefined,
): Promise<ReturnType<typeof resolveConfig>> {
  const {
    rootDir: inlineRootDir,
    srcDir: inlineSrcDir,
    exports: inlineExports,
    ...inlineOptions
  } = inlineConfig;
  const loaded = configFile === false ? null : await loadConfig(viteRoot, configFile);
  const configDir = loaded ? dirname(loaded.path) : viteRoot;
  const fromFile = resolveConfig(loaded?.config ?? {}, configDir);

  return {
    rootDir: inlineRootDir === undefined ? fromFile.rootDir : resolve(viteRoot, inlineRootDir),
    srcDir: inlineSrcDir ?? fromFile.srcDir,
    options: {
      ...fromFile.options,
      ...inlineOptions,
      exports: {
        ...fromFile.options.exports,
        ...inlineExports,
      },
    },
  };
}

/** Configures `build.lib.entry` from source files discovered by vite-magic. */
export function viteMagic(options: ViteMagicPluginOptions = {}): Plugin {
  const { configFile, library: libraryOptions, ...inlineConfig } = options;

  return {
    name: 'vite-magic-tree-shaking',
    enforce: 'pre',
    async config(config): Promise<UserConfig> {
      const library = config.build?.lib;

      if (library === false) {
        throw new Error(
          '[vite-magic-tree-shaking] build.lib cannot be false when using viteMagic()',
        );
      }

      if (library?.entry !== undefined) {
        throw new Error(
          '[vite-magic-tree-shaking] Remove build.lib.entry when using viteMagic(); entries are generated automatically',
        );
      }

      const viteRoot = resolve(process.cwd(), config.root ?? '.');
      const magicConfig = await pluginConfig(viteRoot, inlineConfig, configFile);
      const entry = generateEntries(magicConfig.rootDir, magicConfig.srcDir, magicConfig.options);
      const existingLibrary = library && typeof library === 'object' ? library : {};
      const formats = libraryOptions?.formats ?? magicConfig.options.exports?.formats;

      return {
        build: {
          lib: {
            ...existingLibrary,
            ...libraryOptions,
            ...(formats ? { formats: [...formats] } : {}),
            entry,
          },
        },
      };
    },
  };
}
